{
 "title": "Network RTT",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "www.amazon.com",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "alias": "www.amazon.com",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping_rtt",
     "select": [
      [
       { "params": [ "avg" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=", "value": "aws-london" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "www.amazon.com" }
     ]
    }
   ]
  },
  {
   "title": " www.google.com",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 0 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "alias": "www.google.com",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping_rtt",
     "select": [
      [
       { "params": [ "avg" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=", "value": "aws-london" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "www.google.com" }
     ]
    }
   ]
  },
  {
   "title": "www.wikipedia.org",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 0 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "alias": "www.wikipedia.org",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping_rtt",
     "select": [
      [
       { "params": [ "avg" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=", "value": "aws-london" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "www.wikipedia.org" }
     ]
    }
   ]
  },
  {
   "title": "www.yahoo.com",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 0 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "alias": "www.yahoo.com",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping_rtt",
     "select": [
      [
       { "params": [ "avg" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=", "value": "aws-london" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "www.yahoo.com" }
     ]
    }
   ]
  },
  {
   "title": "www.youtube.com",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 0 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "alias": "www.yahoo.com",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping_rtt",
     "select": [
      [
       { "params": [ "avg" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=", "value": "aws-london" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "www.youtube.com" }
     ]
    }
   ]
  },
  {
   "title": "www.bbc.co.uk",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 0 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "alias": "www.bbc.co.uk",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping_rtt",
     "select": [
      [
       { "params": [ "avg" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=", "value": "aws-london" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "www.bbc.co.uk" }
     ]
    }
   ]
  },
  {
   "title": "amazon.com:443",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 0 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tcp_rtt",
     "select": [
      [
       { "params": [ "avg_rtt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=", "value": "aws-london" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "amazon.com" }
     ]
    }
   ]
  },
  {
   "title": "google.com:443",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 0 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tcp_rtt",
     "select": [
      [
       { "params": [ "avg_rtt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=", "value": "aws-london" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "google.com" }
     ]
    }
   ]
  },
  {
   "title": "wikipedia.org:443",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 0 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tcp_rtt",
     "select": [
      [
       { "params": [ "avg_rtt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=", "value": "aws-london" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "wikipedia.org" }
     ]
    }
   ]
  },
  {
   "title": "yahoo.com:443",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 0 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tcp_rtt",
     "select": [
      [
       { "params": [ "avg_rtt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=", "value": "aws-london" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "yahoo.com" }
     ]
    }
   ]
  },
  {
   "title": "youtube.com:443",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 0 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tcp_rtt",
     "select": [
      [
       { "params": [ "avg_rtt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=", "value": "aws-london" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "youtube.com" }
     ]
    }
   ]
  },
  {
   "title": "bbc.co.uk:443",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 0 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tcp_rtt",
     "select": [
      [
       { "params": [ "avg_rtt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=", "value": "aws-london" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "bbc.co.uk" }
     ]
    }
   ]
  },
  {
   "title": "PING",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "www.amazon.com",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping_rtt",
     "select": [
      [
       { "params": [ "avg" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=", "value": "aws-london" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "www.amazon.com" }
     ]
    },
    {
     "alias": "www.google.com",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping_rtt",
     "select": [
      [
       { "params": [ "avg" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=", "value": "aws-london" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "www.google.com" }
     ]
    },
    {
     "alias": "www.wikipedia.org",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping_rtt",
     "select": [
      [
       { "params": [ "avg" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=", "value": "aws-london" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "www.wikipedia.org" }
     ]
    },
    {
     "alias": "www.yahoo.com",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping_rtt",
     "select": [
      [
       { "params": [ "avg" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=", "value": "aws-london" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "www.yahoo.com" }
     ]
    },
    {
     "alias": "www.youtube.com",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping_rtt",
     "select": [
      [
       { "params": [ "avg" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=", "value": "aws-london" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "www.youtube.com" }
     ]
    },
    {
     "alias": "www.bbc.co.uk",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping_rtt",
     "select": [
      [
       { "params": [ "avg" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=", "value": "aws-london" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "www.bbc.co.uk" }
     ]
    }
   ]
  },
  {
   "title": "TCP RTT",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "amazon - received",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tcp_rtt",
     "select": [
      [
       { "params": [ "received" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=", "value": "aws-london" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "amazon.com" }
     ]
    },
    {
     "alias": "amazon - transmitted",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tcp_rtt",
     "select": [
      [
       { "params": [ "transmitted" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=", "value": "aws-london" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "amazon.com" }
     ]
    },
    {
     "alias": "google - received",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tcp_rtt",
     "select": [
      [
       { "params": [ "received" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=", "value": "aws-london" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "google.com" }
     ]
    },
    {
     "alias": "google - transmitted",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tcp_rtt",
     "select": [
      [
       { "params": [ "transmitted" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=", "value": "aws-london" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "google.com" }
     ]
    },
    {
     "alias": "google - received",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tcp_rtt",
     "select": [
      [
       { "params": [ "received" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=", "value": "aws-london" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "wikipedia.org" }
     ]
    },
    {
     "alias": "google - transmitted",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tcp_rtt",
     "select": [
      [
       { "params": [ "transmitted" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=", "value": "aws-london" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "wikipedia.org" }
     ]
    },
    {
     "alias": "yahoo - received",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tcp_rtt",
     "select": [
      [
       { "params": [ "received" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=", "value": "aws-london" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "yahoo.com" }
     ]
    },
    {
     "alias": "yahoo - transmitted",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tcp_rtt",
     "select": [
      [
       { "params": [ "transmitted" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=", "value": "aws-london" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "yahoo.com" }
     ]
    },
    {
     "alias": "youtube - received",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tcp_rtt",
     "select": [
      [
       { "params": [ "received" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=", "value": "aws-london" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "youtube.com" }
     ]
    },
    {
     "alias": "youtube - transmitted",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tcp_rtt",
     "select": [
      [
       { "params": [ "transmitted" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=", "value": "aws-london" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "youtube.com" }
     ]
    }
   ]
  },
  {
   "title": "amazon reliabilty %",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 13 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "alias": "www.amazon.com",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping_rtt",
     "query": "SELECT mean(percentage) FROM (SELECT (\"received\"/\"transmitted\")*100 AS percentage FROM \"ping_rtt\" WHERE \"host\" = 'www.amazon.com' AND \"region\"='aws-london') WHERE $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "avg" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=", "value": "aws-london" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "www.amazon.com" }
     ]
    }
   ]
  },
  {
   "title": "google reliabilty %",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 13 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "alias": "www.google.com",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping_rtt",
     "query": "SELECT mean(percentage) FROM (SELECT (\"received\"/\"transmitted\")*100 AS percentage FROM \"ping_rtt\" WHERE \"host\" = 'www.google.com' AND \"region\"='aws-london') WHERE $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "avg" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=", "value": "aws-london" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "www.amazon.com" }
     ]
    }
   ]
  },
  {
   "title": "wikipedia reliabilty %",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 13 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "alias": "www.wikipedia.org",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping_rtt",
     "query": "SELECT mean(percentage) FROM (SELECT (\"received\"/\"transmitted\")*100 AS percentage FROM \"ping_rtt\" WHERE \"host\" = 'www.wikipedia.org' AND \"region\"='aws-london') WHERE $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "avg" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=", "value": "aws-london" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "www.amazon.com" }
     ]
    }
   ]
  },
  {
   "title": "yahoo reliabilty %",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 13 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "alias": "www.wikipedia.org",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping_rtt",
     "query": "SELECT mean(percentage) FROM (SELECT (\"received\"/\"transmitted\")*100 AS percentage FROM \"ping_rtt\" WHERE \"host\" = 'www.yahoo.com' AND \"region\"='aws-london') WHERE $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "avg" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=", "value": "aws-london" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "www.amazon.com" }
     ]
    }
   ]
  },
  {
   "title": "youtube reliabilty %",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 13 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "alias": "www.wikipedia.org",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping_rtt",
     "query": "SELECT mean(percentage) FROM (SELECT (\"received\"/\"transmitted\")*100 AS percentage FROM \"ping_rtt\" WHERE \"host\" = 'www.youtube.com' AND \"region\"='aws-london') WHERE $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "avg" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=", "value": "aws-london" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "www.amazon.com" }
     ]
    }
   ]
  },
  {
   "title": "bbc reliabilty %",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 13 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "alias": "www.wikipedia.org",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping_rtt",
     "query": "SELECT mean(percentage) FROM (SELECT (\"received\"/\"transmitted\")*100 AS percentage FROM \"ping_rtt\" WHERE \"host\" = 'www.bbc.co.uk' AND \"region\"='aws-london') WHERE $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "avg" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=", "value": "aws-london" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "www.amazon.com" }
     ]
    }
   ]
  },
  {
   "title": "RELIABILITY %",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "amazon.com",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(percentage) FROM (SELECT (\"received\"/\"transmitted\")*100 AS percentage FROM \"ping_rtt\" WHERE \"host\" = 'www.amazon.com' AND \"region\"='aws-london') WHERE $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "google.com",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(percentage) FROM (SELECT (\"received\"/\"transmitted\")*100 AS percentage FROM \"ping_rtt\" WHERE \"host\" = 'www.google.com' AND \"region\"='aws-london') WHERE $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "wikipedia.org",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(percentage) FROM (SELECT (\"received\"/\"transmitted\")*100 AS percentage FROM \"ping_rtt\" WHERE \"host\" = 'www.wikipedia.org' AND \"region\"='aws-london') WHERE $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "yahoo.com",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(percentage) FROM (SELECT (\"received\"/\"transmitted\")*100 AS percentage FROM \"ping_rtt\" WHERE \"host\" = 'www.yahoo.com' AND \"region\"='aws-london') WHERE $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "youtube.com",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(percentage) FROM (SELECT (\"received\"/\"transmitted\")*100 AS percentage FROM \"ping_rtt\" WHERE \"host\" = 'www.youtube.com' AND \"region\"='aws-london') WHERE $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "bbc.co.uk",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(percentage) FROM (SELECT (\"received\"/\"transmitted\")*100 AS percentage FROM \"ping_rtt\" WHERE \"host\" = 'www.bbc.co.uk' AND \"region\"='aws-london') WHERE $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}